version: "3"

services:
  plex:
    image: ${DOCKER_IMAGE}
    container_name: plex-service
    restart: always
    environment:
      TZ: ${TIMEZONE}
      PLEX_CLAIM: ${PLEX_TOKEN}
      PLEX_UID: 1000
      PLEX_GID: 984
    volumes:
      - "data:/config"
      - "transcode:/transcode"
      - "/mnt/HDNAS/movies:/movies:ro"
      - "/mnt/HDNAS/tvshows:/tvshows:ro"
    networks:
      server-network:
        ipv4_address: 172.40.0.7

volumes: 
  data:
  transcode:

networks:
    server-network:
        external: true
        name: server-containers