version: "3"

services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex-service
    restart: always
    environment:
      TZ: ${TIMEZONE}
      VERSION: docker
      PLEX_CLAIM: ${PLEX_TOKEN}
      PLEX_UID: ${USER_ID}
      PLEX_GID: ${GROUP_ID}
    volumes:
      - "data:/config"
      - "transcode:/transcode"
      - "${MOVIES_FOLDER}:/movies:ro"
      - "${TVSHOWS_FOLDER}:/tvshows:ro"
    network_mode: "host"
  scheduler:
    image: mcuadros/ofelia
    container_name: scheduler
    depends_on:
      - plextraktsync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule: "@every 1h"
      ofelia.job-run.plextraktsync.container: "plextraktsync"
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync
    container_name: plextraktsync
    volumes:
      - sync:/app/config

volumes:
  data:
  transcode:
  sync: