version: "3"

services:
  plex:
    image: ${PLEX_IMAGE}
    container_name: plex-service
    restart: always
    environment:
      TZ: ${TIMEZONE}
      PLEX_CLAIM: ${PLEX_TOKEN}
      ADVERTISE_IP: http://${PLEX_IP}:32400/
      PLEX_UID: 1000
      PLEX_GID: 984
    volumes:
      - "data:/config"
      - "transcode:/transcode"
      - "/mnt/HDNAS/movies:/movies:ro"
      - "/mnt/HDNAS/tvshows:/tvshows:ro"
    network_mode: "host"

volumes: 
  data:
  transcode: